### ISSUE TITLE
No response after clicking Login

### ISSUE THREAD

**Issue by cenyuzhang** [MobileFirst-Platform-Developer-Center/UtilitiesDemoApp#2]
**Summary**:
After the init.sh script setup correctly, and tried to run the app in emulator (either ios or android), there is no response after clicking the login button. The request was processed based on the system console log. Tried both ios emulator 10.x and 9.x.

**Acceptance Criteria**:

- [ ] <TASKS>

**Comment by eng618** [comment]
The resolution was to update Node version running and run on 9.x iOS sim.

**Comment by eng618** [comment]
👍  Okay, to close issue.
